WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))': /session/c2cf0860457743166cba77120e98e581/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x044D56F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c2cf0860457743166cba77120e98e581/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x044D5510>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/c2cf0860457743166cba77120e98e581/screenshot