{"uuid": "60cb837a-4f9a-4f55-9fc1-9b4cb4f96125", "children": ["a19f04e0-8b91-4c00-93e5-56db592ef84c", "51e2a635-22e4-4a17-b072-761c0cb048da", "98563692-4c2d-4afb-977a-d7e9424fbe1a", "aabdac0e-77d5-4cb2-ae08-8bf8a983f2a8", "c6a7c551-d06c-44ed-b37a-c50bae66efe3"], "befores": [{"name": "init_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\15572\\Desktop\\test\\nm_web\\project\\test_case\\conftest.py\", line 12, in init_fixture\n    driver=webdriver.Chrome()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    service_log_path, service, keep_alive)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1652355613656, "stop": 1652355613659}, {"name": "init_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\15572\\Desktop\\test\\nm_web\\project\\test_case\\conftest.py\", line 12, in init_fixture\n    driver=webdriver.Chrome()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    service_log_path, service, keep_alive)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1652355618771, "stop": 1652355618773}, {"name": "init_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\15572\\Desktop\\test\\nm_web\\project\\test_case\\conftest.py\", line 12, in init_fixture\n    driver=webdriver.Chrome()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    service_log_path, service, keep_alive)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1652355623842, "stop": 1652355623844}, {"name": "init_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\15572\\Desktop\\test\\nm_web\\project\\test_case\\conftest.py\", line 12, in init_fixture\n    driver=webdriver.Chrome()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    service_log_path, service, keep_alive)\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 89, in __init__\n    self.service.start()\n  File \"C:\\Users\\15572\\Desktop\\test\\.virtualenv\\nm_web-eiUOuFSS\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1652355628969, "stop": 1652355628971}], "start": 1652355628969, "stop": 1652355633263}